# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNKeyEvent' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RNKeyEvent
  Pod::Spec.new do |s|
    # ...
    s.dependency 'ExpoModulesCore'
  end
end
